/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type {
  IClaimManager,
  IClaimManagerInterface,
} from '../../../contracts/libs/IClaimManager';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'subject',
        type: 'address',
      },
      {
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32',
      },
      {
        internalType: 'uint256',
        name: 'version',
        type: 'uint256',
      },
    ],
    name: 'hasRole',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class IClaimManager__factory {
  static readonly abi = _abi;
  static createInterface(): IClaimManagerInterface {
    return new utils.Interface(_abi) as IClaimManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IClaimManager {
    return new Contract(address, _abi, signerOrProvider) as IClaimManager;
  }
}
